apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-default
  namespace: argocd
spec:
  description: "Ephemeral environments for tenant default"
  sourceRepos:
    - "https://github.com/dusttostars/vcluster-ephemeral-envs.git"
    - "https://charts.loft.sh"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: tenant-default
  clusterResourceWhitelist:
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRoleBinding"
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: "apps"
      kind: "*"
    - group: "rbac.authorization.k8s.io"
      kind: "*"
