apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-controller
  labels:
    ephemeral.io/component: controller
subjects:
  - kind: ServiceAccount
    name: cleanup-controller
    namespace: ephemeral-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cleanup-controller
