---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ephemeral-system
spec:
  encryptedData:
    token: AgAEs9myf/mjuEiCOQIknCeK6ZnOtK/IK0Hes5HZus1z5Nw8yx4DryEnKmh+/95JtdcdiRFZzVmV5ZA1qXEI//xDgucqqR/qnuysD8n/8BC2rWlqeL55+z5rxeZFuNohPQ0E6Ap1ECTFNorLrKGHf7p7wu8QaKY2dkpeGfm/B5R0WR+meg2Pyyxg9m6gLrqrGoejZBGZepU+npil3V8YqZYiWeQ/0aS4CoECLSsOuyoTY+YR2S6xAR1FzkYU7BDMRrOkc8/Sz+fM1XatppuLTuUAQNOJBHk2IfxL/HhpuJlIoSKJyHTBSCOvpSHkk86pzWo+mlsb7UrSe3taSQIJEncSwsf0dLrYdSttXH+LC7aEVQRsxGyRgKN/5OVTNnef4+U76qPx+jkwPs8b86S5Jwj+cuJtUD5oULR7I/mYZEps+X20CXrSEKpoLVhw6H4lOMtcRT5rZ9jehoC0dewHRKETN0M1qw68eQrepqS190SJ2eNAX2liqupaN2XJzSAtQnrmsDrreOUAf2bQQnA33xZWKJ0AM4DiRI7GuFM4hEDkbpFtx7QyGaA+6+MygQqZMLpX6H0MMKApfgOwBzjUiOt1U3XGkGoibOJXxIjYg8EfDVsnqNTUP3eT/da31RutgOFs907ynIznPFiLVASs5VJWP/fo5Mof2du1sQRhOvJ4iW33ygS5xnXe414LRq7906t0Opn10N/2HwMVzyBA/koKo+2aIwxxnBGq8noUc5mhFb+mALtU21pbEW/xj2KZgt7IotWGNjsE9cFMxQRAVNFPFTmQC6Ol/PV/rEExQbLEpFzImQ9SZNAdK7+fbmQ=
    username: AgBL4JCSwT75/Ln1932vP7p9/ok+dpRaUXpfgq3P3B7pnG83wyJzn0DbCuzJ0MRpUKZR6mQKBghz6ES0QA/nNwzSQ64fbmZxlub6PjCnQzo94dCBu2v6kh1zdotechMbYN/LEVETSa2uUT+klnLKIeUETkBWVJoOGC7OS82fWVTTi/uWJd8JNInkX6N6pqK7jJC8zNm9juiFqZMmrLvZkYm2WHdN94g84ZLz+iBa+LjXi3qaEtX0+r4ONiqLioIaxa1OD2eZUqbYi3IJ1vBY+V/Hc51DcE4eS7HpmewvxBXexstlZIvVB3HgkdrUxIt0gCXeaEgk3Hwfw36zNXNHyX68q2Hu8laIr05a/fsQxVM21Uue2KNIx70Z/JnVR3PauT88P7XQ0DyB36OR2i+ArbKLu9UeCHzkS18+5m17BrJDIlNmqbZz4CfEPU273NGTe6YP+soCI7zRoIvg0YyYArLf/oxQvpWpc5eM6JuB3fToQikEFJuH8F5wgfSgD9JQBM6TWlu082YdbFhRkltznFUtPr2ubbZ/0akEHMBw9PuQwUSeb/2bjwYlRwhRcXx/SEO+WKAPyhmiJpO/g/Zm6COoJ0flljJqEaLoyK3WtjhIbyB0TnpWrXMR8v3nSyI06PFBSCezCZTsS7ENr6MWNmcv9WY7L6QJZeJX5V/cTTeKP19KYL9zNmqrJp22aW/Y8g6PtTgxKe+h0w5kePcODg==
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: ephemeral-system
