image:
  repository: ghcr.io/dusttostars/vcluster-ephemeral-envs/app
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

port: 8080

gitBranch: ""
gitCommit: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
