apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-feat-nginx-simple
  namespace: argocd
  labels:
    ephemeral.io/tenant: "default"
    ephemeral.io/branch: "feat-nginx-simple"
    ephemeral.io/ttl: "2h"
    ephemeral.io/created-at: "20260414T205226Z"
    ephemeral.io/managed-by: "ephemeral-controller"
spec:
  project: tenant-default
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: "0.19.*"
    helm:
      values: |
        syncer:
          extraArgs:
            - --out-kube-config-server=https://vcluster-feat-nginx-simple.tenant-default.svc.cluster.local
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        vcluster:
          image: rancher/k3s:v1.29.1-k3s2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
        sync:
          ingresses:
            enabled: true
          services:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
